### ISSUE TITLE
Investigate the plugin-free use case

### ISSUE THREAD

**Issue by DamonOehlman** [rtc-io/rtc-screenshare#13]
As per discussion with @maxogden

**Comment by maxogden** [comment]
my use case is atom-shell, where you can do this out of the box w/ no special settings:

```
var constraints = {
  audio: false,
  video: {
    mandatory: {
      chromeMediaSource: 'screen',
      maxWidth: 1280,
      maxHeight: 720,
      maxFrameRate: 15
    },
    optional: []
  }
}
```

**Comment by DamonOehlman** [comment]
Cool, I'll have a play around with the package in an atom-shell context and see if I can go all Modernizr and detect support for `chromeMediaSource: 'screen'` before attempting to communicate with a plugin...

**Comment by DamonOehlman** [comment]
So it's not possible (as far as I can tell) to determine whether or not can successfully make a `chromeMediaSource: 'screen'` request or require an extension, without at least attempting to capture media.   This unfortunately means that it's not possible to do this given the scope of the `rtc-screenshare` package is "do no capture, just get constraints".

But because modules, packages, etc I was able to create [`rtc-screen`](https://github.com/rtc-io/rtc-screen) which feels really nice and achieves the same result regardless of whether it is being called within a webapp or an atom app.  Still needs firefox support - see #14 but I'll take care of that soon :)

So I consider that a win :)
