### ISSUE TITLE
If possible, When installing extension avoid permission request to all tabs.

### ISSUE THREAD

**Issue by jawandarajbir** [rtc-io/rtc-screenshare#8]
When you install extesnion, It currently request for following permissions
![capture](https://cloud.githubusercontent.com/assets/3058693/5445899/2b6f79f6-850c-11e4-86d2-b8e6334dd967.PNG)

Can we somehow remove the "tabs" permission from the manifest.json?

**Comment by DamonOehlman** [comment]
Permissions have been brought in as tight as they can be.  Tabs permission [has been removed](https://github.com/rtc-io/rtc-screenshare/blob/master/extension/src/manifest.json#L17) but a similar message is displayed for the domain that has been specified in the manifest.

**Comment by jawandarajbir** [comment]
Thanks Damon
